[SW-205252][SW-204329] fixed measurement path bug
fixed this error, that happened due to wrong condition:
File "/root/optimum-habana-fork/examples/text-generation/quantization_tools/unify_measurements.py",
line 56, in unify_measurements
    with open(measurements_paths[0], "r") as origin, open(unified_json_path, "w") as copy:
IndexError: list index out of range

Change-Id: I5ca42a4bc88077f6ce84f07b317aaf274a9ebcb4